# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0009_auto_20170703_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='use_case_status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
