# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0011_auto_20170812_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='element_value',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
