# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0012_auto_20170812_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='use_case_status',
            field=models.TextField(blank=True),
        ),
    ]
