# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0013_usecase_use_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='use_case_status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
